name: Node CI + Docker Build & Push

on:
  push:
    branches: [  development ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests
      - name: Run tests
        run: npm test || echo "No tests"

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Setup Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/recipe-ui:latest .

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/recipe-ui:latest

      # Cloud deployment: TO-DO
      # 5️⃣ Push Docker image to Azure container registry
      # - name: Login to Azure
      #   uses: azure/docker-login@v2
      #   with:
      #     login-server: myacrname.azurecr.io
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Tag image
      #   run: |
      #     docker tag recipe-backend:latest myacrname.azurecr.io/recipe-ui:latest

      # - name: Push image
      #   run: |
      #     docker push myacrname.azurecr.io/recipe-ui:latest

      # 6 Login to Azure and run terraform file: main.tf, acr.tf, aks.tf
      # 7 Login to AKS cluster and run deployment.yaml, service.yaml files