name: Terraform Infra

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-tfstate-ui" \
            -backend-config="storage_account_name=sttfstaterecipewebappui" \
            -backend-config="container_name=tfstate-ui" \
            -backend-config="key=recipe-webapp.tfstate-ui"
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra

      - name: Terraform Apply
        if: github.ref != 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: infra
