name: Node CI + Docker Build & Push

on:
  push:
    branches: [  QA ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests
      - name: Run tests
        run: npm test || echo "No tests"

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write
      id-token: write

    environment:
      name: test

    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/recipe-ui-qa:${{ github.sha }}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push
        run: |
          docker build -t ${{ steps.image.outputs.image }} .
          docker push ${{ steps.image.outputs.image }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image.outputs.image }}
          format: table
          output: trivy-report.txt
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Save Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt    

  deploy-qa:
    needs: docker-build-push
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ─────────────────────────────────────
      # Terraform read-only (state source)
      # ─────────────────────────────────────
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (infra state only)
        working-directory: infra
        env:
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-tfstate-ui" \
            -backend-config="storage_account_name=sttfstaterecipewebappui" \
            -backend-config="container_name=tfstate-ui" \
            -backend-config="key=recipe-webapp.tfstate-ui"

      - name: Read use_slots from Terraform
        id: tf
        working-directory: infra
        run: |
          echo "use_slots=$(terraform output -raw use_slots)" >> $GITHUB_OUTPUT

      - name: Enable managed identity for ACR pull
        run: |
          az webapp config set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --generic-configurations '{"acrUseManagedIdentityCreds": true}'

      - name: Deploy to main app
        if: steps.tf.outputs.use_slots != 'true'
        run: |
           az webapp config set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --linux-fx-version "DOCKER|${{ secrets.ACR_LOGIN_SERVER }}/recipe-ui-qa:${{ github.sha }}"

      - name: Restart main app
        if: steps.tf.outputs.use_slots != 'true'
        run: |
          az webapp restart \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Deploy to slot
        if: steps.tf.outputs.use_slots == 'true'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: staging
          images: ${{ secrets.ACR_LOGIN_SERVER }}/recipe-ui-prod:${{ github.sha }}

      - name: Wait for slot warm-up
        if: steps.tf.outputs.use_slots == 'true'
        run: sleep 25

      - name: Swap staging to production
        if: steps.tf.outputs.use_slots == 'true'
        run: |
          az webapp deployment slot swap \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --slot staging \
            --target-slot production
